modules/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired


class AddForm(FlaskForm):
    name = StringField('Country Name', validators=[DataRequired()])
    submit = SubmitField('Submit')

app.py
from flask import Flask
from flask_bootstrap import Bootstrap
from modules import views


application = Flask(__name__)
application.testing = True
application.secret_key = b'_5#y2L"F4Q8z\n\xec]/'


if __name__ == "__main__":
    Bootstrap(application)
    application.register_blueprint(views.bp)
    application.run(debug=True)

modules/views.py
import firebase_admin
from firebase_admin import credentials
from firebase_admin import db

from flask import Blueprint
from flask import render_template, redirect, url_for
from modules import forms


bp = Blueprint('views', __name__)
database_url = 'https://test-project-ceef3-default-rtdb.firebaseio.com/'

cred = credentials.Certificate("dbkey.json")
firebase_admin.initialize_app(
    cred,
    {'databaseURL': database_url}
)


class DuplicateError(Exception):
    def __init__(self, name):
        self.message = f'Cтрана {name} уже есть в списке'
        super().__init__(self.message)

@bp.route("/test")
def test():
    return 'hello world'


@bp.route("/")
@bp.route("/home")
def home():
    return render_template('home.html', title='home')


@bp.route("/countries_get", methods=['GET', 'POST'])
def get():
    ref = db.reference("/countries/")
    countries = ref.get()
    return render_template('get.html', data=countries)


@bp.route("/countries_add", methods=['GET', 'POST'])
def add():
    form = forms.AddForm()
    ermessage = ''
    if form.validate_on_submit():
        try:
            print(form.name.data)
            ref = db.reference("/countries/")
            countries = ref.get()
            if form.name.data in countries:
                raise DuplicateError(form.name.data)
            countries.append(form.name.data)
            ref = db.reference("/")
            ref.update({"countries":countries})
            return redirect('/countries_get')
        
        except DuplicateError as e:
            ermessage = str(e)
        except Exception as e:
            print(e)
            ermessage = 'Ошибка - попытайтесь снова'
    return render_template('add.html', form=form, error=ermessage)

templates/add.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles %}
{{ super() }}
	<style>
		body { background: #e8f1f9; }
	</style>
{% endblock %}


{% block title %}
Добавить
{% endblock %}


{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto">

      <h1 class="pt-5 pb-2">Добавить Страну</h1>

      {{ wtf.quick_form(form) }}

      <p class="pt-5"><strong>{{ error }}</strong></p>

      <a href="{{ url_for('views.get') }}">Просмотреть таблицу</a>

    </div>
  </div>
</div>

{% endblock %}

templates/get.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles %}
{{ super() }}
	<style>
		body { background: #e8f1f9; }
	</style>
{% endblock %}


{% block title %}
Страны
{% endblock %}


{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto">
      <ul>
      {%for i in data%}
        <li>{{i}}</li>
      {%endfor%}
      </ul>
      <a href="{{ url_for('views.add') }}">Добавить Страну</a>
    </div>
  </div>
</div>

{% endblock %}

templates/home.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles %}
{{ super() }}
	<style>
		body { background: #e8f1f9; }
	</style>
{% endblock %}


{% block title %}
Главная
{% endblock %}


{% block content %}

<div class="container">
  <div class="row">
    <div class="col-lg-12">

        <a href="{{ url_for('views.add') }}">Добавить Страну</a>
        <br>
        <br>
        <a href="{{ url_for('views.get') }}">Просмотреть таблицу</a>

    </div>
  </div>
</div>

{% endblock %}